services:
  web:
    build: .
    environment:
      - DEBUG=${DEBUG:-0}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db
      - DB_NAME=projectdb
      - DB_USER=projectuser
      - DB_PASSWORD=${DB_PASSWORD}
      # - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      # - HUGGINGFACEHUB_API_TOKEN=${SECRET_HF_TOKEN}
      # - HF_ENDPOINT=https://router.huggingface.co
    ports:
      - "8000:8000"

    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: projectdb
      POSTGRES_USER: projectuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
