# Generated by Django 5.0.1 on 2026-01-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_question_document_question_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
